version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:3000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  # browser-extension:
  #   build: ./browser-extension
  #   volumes:
  #     - ./browser-extension:/app
  #     - /app/node_modules # Anonymes Volume für node_modules
  #   # Keine Ports oder depends_on, da dies keine laufende Service ist, sondern nur zum Bauen verwendet wird

  # db: # Nicht verwendet, da wir Neon.tech verwenden
  #   image: postgres:13
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   env_file:
  #     - ./backend/.env # Verwende die gleiche .env für DB-Variablen
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data: # Nicht verwendet

networks:
  trustme-network:
    driver: bridge